<a href="https://colab.research.google.com/github/AnirudhPhophalia/1024160120_UCS420_CC_Assignments/blob/main/cc_ac3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

## Q.1 Create a dataset as follow in the table.

In [3]:
data = {
    "Tid": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Refund": ["Yes", "No", "No", "Yes", "No", "No", "Yes", "No", "No", "No"],
    "Marital Status": ["Single", "Married", "Single", "Married", "Divorced", "Married", "Divorced", "Single", "Married", "Single"],
    "Taxable Income": [125, 100, 70, 120, 95, 60, 220, 85, 75, 90],
    "Cheat": ["No", "No", "No", "No", "Yes", "No", "No", "Yes", "No", "Yes"]
}
df = pd.DataFrame(data)
display(df)

   Tid Refund Marital Status  Taxable Income Cheat
0    1    Yes         Single             125    No
1    2     No        Married             100    No
2    3     No         Single              70    No
3    4    Yes        Married             120    No
4    5     No       Divorced              95   Yes
5    6     No        Married              60    No
6    7    Yes       Divorced             220    No
7    8     No         Single              85   Yes
8    9     No        Married              75    No
9   10     No         Single              90   Yes

## Q.2 From the above table that you have created, locate row 0, 4, 7 and 8 using DataFrame.

In [4]:
df.iloc[0]

Tid                    1
Refund               Yes
Marital Status    Single
Taxable Income       125
Cheat                 No
Name: 0, dtype: object

In [7]:
selected_rows = df.iloc[[0, 4, 7, 8]]
display(selected_rows)

   Tid Refund Marital Status  Taxable Income Cheat
0    1    Yes         Single             125    No
4    5     No       Divorced              95   Yes
7    8     No         Single              85   Yes
8    9     No        Married              75    No

## Q.3 Navigate the DataFrame and do the following task for the table created in question 1:
1. Select row from index 3 to 7.
2. Select row from index 4 to 8, and column 2 to 4.
3. Select all rows with column index 1 to 3 (include index 3 during selection).

In [9]:
sel1 = df.iloc[3:7]
sel2 = df.iloc[4:8, 2:4]
sel3 = df.iloc[:,1:4]

print(sel1)
print(sel2)
print(sel3)

   Tid Refund Marital Status  Taxable Income Cheat
3    4    Yes        Married             120    No
4    5     No       Divorced              95   Yes
5    6     No        Married              60    No
6    7    Yes       Divorced             220    No
  Marital Status  Taxable Income
4       Divorced              95
5        Married              60
6       Divorced             220
7         Single              85
  Refund Marital Status  Taxable Income
0    Yes         Single             125
1     No        Married             100
2     No         Single              70
3    Yes        Married             120
4     No       Divorced              95
5     No        Married              60
6    Yes       Divorced             220
7     No         Single              85
8     No        Married              75
9     No         Single              90

## Q.4 Read a csv file and display its first five rows.  
Note-: Download dataset from https://www.kaggle.com/datasets/uciml/iris

In [11]:
data = pd.read_csv("Iris.csv")
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

## Q.5 From the csv file (uploaded in the Q.4) delete row 4, and delete column 3. Display the result.

In [12]:
data.drop(4, inplace=True)
data.drop(data.columns[3], axis=1, inplace=True)
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalWidthCm      Species
0   1            5.1           3.5           0.2  Iris-setosa
1   2            4.9           3.0           0.2  Iris-setosa
2   3            4.7           3.2           0.2  Iris-setosa
3   4            4.6           3.1           0.2  Iris-setosa
5   6            5.4           3.9           0.4  Iris-setosa

## Q.6 Create a sample dataset (employees.csv) containing information about employees in a company.

In [13]:
data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 70000, 65000, 55000, 60000],
    "Years_of_Experience": [4, 8, 10, 3, 12],
    "Joining_Date": ["2020-03-15", "2017-07-19", "2013-06-01", "2021-02-10", "2010-11-25"],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5]
}
df = pd.DataFrame(data)
display(df)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [15]:
df.shape

(5, 10)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes

In [23]:
df.describe()

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

In [24]:
df.head()

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [25]:
df.tail(3)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [27]:
avg = df["Salary"].mean()
print(avg)

bonus = sum(df['Bonus'])
print(bonus)

young = min(df['Age'])
print(young)

rate = max(df['Rating'])
print(rate)

60000.0
27500
28
4.7

In [28]:
sorted_df = df.sort_values(by='Salary', ascending=False)
display(sorted_df)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

### Add a new column that categorizes employees based on their performance rating:
Excellent for ratings >= 4.5

Good for ratings >= 4.0 but < 4.5

Average for ratings < 4.0

In [29]:
def categorize_rating(rating):
    if rating >= 4.5:
        return 'Excellent'
    elif rating >= 4.0:
        return 'Good'
    else:
        return 'Average'

df['Performance_Category'] = df['Rating'].apply(categorize_rating)
display(df[['Name', 'Rating', 'Performance_Category']])

      Name  Rating Performance_Category
0    Alice     4.5            Excellent
1      Bob     4.0                 Good
2  Charlie     3.8              Average
3    Diana     4.7            Excellent
4   Edward     3.5              Average

### Identify missing values in the DataFrame.

In [30]:
missing_values = df.isnull().sum()
display(missing_values)

Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

### Rename the 'Employee_ID' column to 'ID'.

In [31]:
df = df.rename(columns={'Employee_ID': 'ID'})
display(df.head())

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

### Find all employees who have more than 5 years of experience.

In [32]:
experienced_employees = df[df['Years_of_Experience'] > 5]
display(experienced_employees[['Name', 'Years_of_Experience']])

      Name  Years_of_Experience
1      Bob                    8
2  Charlie                   10
4   Edward                   12

### Find all employees who belong to the IT department.

In [33]:
it_employees = df[df['Department'] == 'IT']
display(it_employees[['Name', 'Department']])

      Name Department
1      Bob         IT
2  Charlie         IT

### Modify the dataset by adding a new column, Tax, which deducts 10% of the Salary.

In [34]:
df['Tax'] = df['Salary'] * 0.10
display(df[['Name', 'Salary', 'Tax']].head())

      Name  Salary     Tax
0    Alice   50000  5000.0
1      Bob   70000  7000.0
2  Charlie   65000  6500.0
3    Diana   55000  5500.0
4   Edward   60000  6000.0

### Save the modified DataFrame (with added columns) to a new CSV file.

In [36]:
df.to_csv('employees_modified.csv', index=False)